### ISSUE TITLE
Charting Custom notes?

### ISSUE THREAD

**Issue by mable-yeah** [PrincessMtH/SNIFF#12]
Is there any way to Chart custom note types with this, or would that have to be done manually in the game instead?

**Comment by PrincessMtH** [comment]
there's no custom note types in fnf so idk lol! unless you just mean week 7 alt notes in which case u gotta set porta on the note

**Comment by mable-yeah** [comment]
Oh, well I was talking about how in most non default fnf engines theres like kill notes n shit specifically i needed to chart gf note's in psych engine, i ended up just charting it normally in the built in chart editor lol
