### ISSUE TITLE
How do I use the "BPM CH"?

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [PrincessMtH/SNIFF#17]
I have no idea 😑

**Comment by SomeGuyWhoLovesCoding** [comment]
I wanted to change the bpm from 160 to 180.

**Comment by SomeGuyWhoLovesCoding** [comment]
nvm

**Comment by MultiArtsYT1** [comment]
> I wanted to change the bpm from 160 to 180.

Did you ever find out how?

**Comment by SomeGuyWhoLovesCoding** [comment]
No

> > I wanted to change the bpm from 160 to 180.
> 
> Did you ever find out how?

Sorry for late reply

**Comment by SomeGuyWhoLovesCoding** [comment]
And yeah I figured it how

**Comment by SomeGuyWhoLovesCoding** [comment]
It's why I closed this issue with nvm

**Comment by MultiArtsYT1** [comment]
> It's why I closed this issue with nvm

Could you tell me how you fixed this issue

**Comment by SomeGuyWhoLovesCoding** [comment]
> > It's why I closed this issue with nvm
> 
> Could you tell me how you fixed this issue

I made that issue 2 years ago and that was me back then when I was mew to sniff. I don't use sniff anymore cause I'm working my own custom fnf engine and I don't want to chart with fl studio. No thanks.
