### ISSUE TITLE
Wont generate chopped notes

### ISSUE THREAD

**Issue by yelleko1** [PrincessMtH/SNIFF#18]
Notes like these 
![fghj](https://user-images.githubusercontent.com/110422450/208303710-657d1a6c-521c-4ab4-8ac9-9fbb16ac6811.PNG)
wont generate. help please?

**Comment by PrincessMtH** [comment]
SNIFF doesn't work with grouped notes, I believe FL automatically groups chops generated with their chopping tool. Select the group and press Alt-G to ungroup.

**Comment by yelleko1** [comment]
Thanks
