### ISSUE TITLE
Porta Notes not detected

### ISSUE THREAD

**Issue by Cheemsandfriends** [PrincessMtH/SNIFF#2]
Hello,
Uhm So when I try to chart with Sniff and I check the Porta checkbox It doesn't detect the notes as an individual alt note. It detects like a simple note.

**Comment by PrincessMtH** [comment]
Can you provide a generated .json file to showcase the issue?

**Comment by Cheemsandfriends** [comment]
Ok. I sent you a json example of cocoa but the mom notes are with Porta, and the flp of the cocoa song for check.
I'm new with SNIFF so I want to think that I made a mistake prob lol

[cocoa example.zip](https://github.com/PrincessMtH/SNIFF/files/7112364/cocoa.example.zip)

A small video for seeing what's the problem lol

https://user-images.githubusercontent.com/84867412/132141863-db563024-21c1-4513-9b60-00db83b775e4.mp4

**Comment by PrincessMtH** [comment]
Using the .flp you provided, I was able to convert it with porta notes being processed no problem, so I'm not sure what the issue would be. The code where they're processed is very simple, and only checks for a single bit. It can be seen here: https://github.com/PrincessMtH/SNIFF/blob/60a317ce8669176293662c665585603116296c09/SNIFF/Program.cs#L552-L553
I don't know if there's anything that can really throw this off. Do you know if there's anything about your setup that might?

**Comment by Cheemsandfriends** [comment]
Maybe i have an outdated or bad FL studio or Sniff lol

**Comment by Cheemsandfriends** [comment]
Maybe is Fl Studio compatibility?

**Comment by PrincessMtH** [comment]
As I said before, I used the exact .flp file you provided. I can't actually open it myself as I use FL 11 to begin with, but the problem isn't with the file seeing as it worked properly.

**Comment by Cheemsandfriends** [comment]
Maybe it's the Sniff app?
Idk. It could be since you made the last public release on 30 of April.

**Comment by Cheemsandfriends** [comment]
I'll switch to fl studio 11 since there is 100% sure it'll work right lol
