### ISSUE TITLE
is it possible to add midi support?

### ISSUE THREAD

**Issue by cabfile** [PrincessMtH/SNIFF#20]
i dont have fl studio, but SNIFF only seems to support .flp

**Comment by PrincessMtH** [comment]
yeah you can add midi support if you want

**Comment by cabfile** [comment]
bruh
i dont have the skills necessary to do it myself and with the title i was asking you to do it (especially considering you were able to write the whole program in the first place)

**Comment by PrincessMtH** [comment]
i shan't

**Comment by libauror-a** [comment]
iirc there's something called midi2fnf on gamebana by nyxtheshield (the guy who made the x!event mod)

**Comment by cabfile** [comment]
that one doesnt work
