### ISSUE TITLE
.jsons just not exporting

### ISSUE THREAD

**Issue by AtonalShift** [PrincessMtH/SNIFF#6]
I have no clue why this keeps happening. When I select an flp for the tool to export as a json, it just processes the notes and says "press any key to close".

**Comment by PrincessMtH** [comment]
typically this means it didn't find any suitable notes. to improve results, please ensure that your channel is
- the top channel in the rack
- preferably an instance of FPC, if not, make sure there are no FPC channels
- not using any grouped notes
- selected when saving the project
- set up in the first pattern, and the first pattern is selected while saving

and that your notes are in the correct places. if after that it still doesn't work, please send over the .flp in question

**Comment by AtonalShift** [comment]
Thanks!
